version: '3'
services:
  postgres:
    image: postgres:latest
    container_name: nest-postgres
    env_file:
      - ./cook-unity-engine/.env
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: