version: '3'
services:

  postgres:
    image: postgres:latest
    container_name: nest-postgres
    env_file:
      - ./cook-unity-engine/.env
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - engine_network

  engine_service:
    build:
      context: ./cook-unity-engine
      dockerfile: Dockerfile
    container_name: nest-app
    ports:
      - "3000:3000"
    env_file:
      - ./cook-unity-engine/.env
    depends_on:
      - postgres
    networks:
      - engine_network
volumes:
  postgres-data:
networks:
  engine_network:
    driver: bridge